# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: Nexus IQ for Azure DevOps@0
  inputs:
    serverUrl: 'https://48298905.ngrok.io'
    serverUsername: 'admin'
    serverPassword: 'admin123'
    applicationId: 'app123'
    scanDirectory: '/home/vsts/work/1/s/webgoat-container/target'
    stage: 'build'
    scanTargets: '**\*.nupkg,**\*.js'
